spring:
  cloud:
    gateway:
      routes:
        - id: swiggy-app
          uri: lb://MATCH-SERVICE
          predicates:
            - Path=/match/**
          filters:
            - AuthenticationFilter


        - id: restaurant-service
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: SPORTATHON-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/