server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportathon
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: REGISTRATION-SERVICE
  #  config:
  #    import: optional:configserver:http://localhost:8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
